workflows:
  expo-calculator-workflow:
    name: Expo Calculator Workflow
    max_build_duration: 60
    environment:
      vars:
        EXPO_USERNAME: Encrypted: your_encrypted_username
        EXPO_PASSWORD: Encrypted: your_encrypted_password
      node: 18.16.0
      flutter: none
      cocoapods: default
      xcode: none
      java: default
      android:
        gradle: default
        cache:
          - ~/.gradle
          - ~/.android/build-cache
          - ~/.npm
    scripts:
      - name: Install dependencies
        script: npm install --legacy-peer-deps
      - name: Start build
        script: npx expo prebuild
      - name: Build APK
        script: npx eas build --platform android --profile preview
    artifacts:
      - build/android/*.apk
      - build/android/app-release.apk
    cache:
      paths:
        - ~/.gradle
        - ~/.android/build-cache
        - ~/.npm
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify_on_success: true
        notify_on_failure: true
