workflows:
  android-build:
    name: Android APK Build
    max_build_duration: 60
    environment:
      vars:
        EXPO_TOKEN: Encrypted: your_encrypted_expo_token
      node: latest
      flutter: stable
      cocoapods: default
      ruby: default
    scripts:
      - name: Install Dependencies
        script: |
          npm install
          npm install -g expo-cli
      - name: Prebuild Android
        script: |
          expo prebuild --platform android
      - name: Build APK
        script: |
          eas build --platform android --profile production
    artifacts:
      - build/android/*.apk

