triggers:
  - type: push
    branch: main

workflows:
  expo-android-workflow:
    name: Expo Android Workflow
    environment:
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
        KEYSTORE_BASE64: $KEYSTORE_BASE64
        KEYSTORE_PASSWORD: $KEYSTORE_PASSWORD
        KEY_ALIAS: $KEY_ALIAS
        KEY_PASSWORD: $KEY_PASSWORD
    scripts:
      - name: Install dependencies
        script: yarn install
      - name: Login to Expo
        script: npx expo login --token $EXPO_TOKEN
      - name: Build Android app
        script: npx expo build:android --no-wait
