workflows:
  expo-calculator-workflow:
    name: Expo Calculator Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      node: 18.17.1
      npm: 9.8.1
      vars:
        NODE_ENV: "production"
      # If you need Android SDK explicitly:
      android:
        components:
          - tools
          - platform-tools
          - build-tools-33.0.0
          - android-33
    scripts:
      - name: Install dependencies
        script: |
          echo "Installing npm dependencies..."
          npm install --legacy-peer-deps
      - name: Prebuild Expo
        script: |
          echo "Running Expo prebuild..."
          npx expo prebuild
      - name: Build Android APK
        script: |
          echo "Building Android APK..."
          npx eas build --platform android --profile preview --non-interactive
    artifacts:
      - build/**/android/*.apk
    publishing:
      email:
        recipients:
          - "youremail@example.com"
        notify_on_success: true
        notify_on_failure: true
