workflows:
  expo-workflow:
    name: Expo Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      node: 20.11.1   # ✅ Node.js version
      expo_token: $EXPO_TOKEN
      vars:
        EXPO_ANDROID_KEYSTORE_PASSWORD: $EXPO_ANDROID_KEYSTORE_PASSWORD
        EXPO_ANDROID_KEY_ALIAS_PASSWORD: $EXPO_ANDROID_KEY_ALIAS_PASSWORD
        EXPO_ANDROID_KEY_ALIAS: $EXPO_ANDROID_KEY_ALIAS
    
    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build Android APK
        script: |
          npx expo export --platform android
          npx expo build:android -t apk

      # If you also want iOS builds, uncomment below
      # - name: Build iOS IPA
      #   script: |
      #     npx expo build:ios -t archive

    artifacts:
      - android/*.apk
      - ios/*.ipa
