workflows:
  expo-workflow:
    name: Expo Build Workflow
    environment:
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
        ANDROID_KEYSTORE: $ANDROID_KEYSTORE
        ANDROID_KEYSTORE_PASSWORD: $ANDROID_KEYSTORE_PASSWORD
        ANDROID_KEY_ALIAS: $ANDROID_KEY_ALIAS
        ANDROID_KEY_PASSWORD: $ANDROID_KEY_PASSWORD
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Login to Expo
        script: npx expo login --token $EXPO_TOKEN
      - name: Build Android app
        script: npx expo build:android --no-wait
