workflows:
  android-workflow:
    name: Android APK Build
    environment:
      groups:
        - default
    scripts:
      - name: Install dependencies
        script: |
          yarn install
      - name: Build APK
        script: |
          expo export --platform android
    artifacts:
      - build/**/*.apk
