workflows:
  my_awesome_app_workflow:
    name: My Awesome Calculator Workflow
    max_build_duration: 60
    environment:
      vars:
        EXPO_USERNAME: "encrypted:your_encrypted_username"
        EXPO_PASSWORD: "encrypted:your_encrypted_password"
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Build APK
        script: |
          npx expo prebuild
          npx eas build --platform android
    artifacts:
      - build/**/*.apk
      - android/app/build/outputs/**/*.apk   # <-- added explicit Android artifact path
    publishing:
      expo: {}
