workflows:
  expo-workflow:
    name: Expo Android Build
    environment:
      node: 18
      package_manager: yarn
    scripts:
      - name: Install dependencies
        script: |
          yarn install
      - name: Prebuild Expo (generate native projects)
        script: |
          npx expo prebuild --platform android
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your@email.com
